version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - '8000:8000'
    environment:
      WALLET_PRIVATE_KEY: ${WALLET_PRIVATE_KEY}
      POLYMARKET_API_KEY: ${POLYMARKET_API_KEY}
      KELLY_FRACTION: ${KELLY_FRACTION}
      DATABASE_URL: ${DATABASE_URL}
      INFURA_ID: ${INFURA_ID}
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - '3000:80'
    depends_on:
      - backend
